### ISSUE TITLE
Request support for product

### ISSUE THREAD

**Issue by DaveTech78** [bitfocus/companion-module-softron-ontheairvideo#3]
It's older but I'm eager to use a mac program for playouts into live streams and some broadcast shows - it's called "ONTHEAIR Video"
We use an Alpha and bravo channel via a declink for the output, works well. But being able to streamline the workflow would be amazing!

**Comment by josephdadams** [comment]
@DaveTech78 please submit as individual requests

**Comment by bryce-seifert** [comment]
@DaveTech78 OnTheAir Video has an existing [module](https://github.com/bitfocus/companion-module-softron-ontheairvideo).

**Comment by DaveTech78** [comment]
Oh my bad, thank you for the response. I am having problems with connection - is there any known issues? Does it work with version 3.5.1 ?

**Comment by bryce-seifert** [comment]
@josephdadams I think this can be closed.

**Comment by bryce-seifert** [comment]
@DaveTech78 Do you have the full version of OnTheAir? (Not express)

**Comment by bryce-seifert** [comment]
@josephdadams Sorry I didn’t see the additional comment about the connection issue

**Comment by bryce-seifert** [comment]
@DaveTech78 After having a moment to look into this, it seems like the first version that allows API control is OnTheAir 4.0.


So in order to use the module, please update to 4.0 or greater

**Comment by DaveTech78** [comment]
Thanks - I suspected as much.

**Comment by bryce-seifert** [comment]
@josephdadams Ok this can actually be closed for real now! Thanks!
